#!/bin/bash

#########################################################################################
# This script would list the object of the bucket that are not owned by the bucket owner.
#########################################################################################

if [[ -z $1 ]]; then
	echo "Usage $0 bucket_name [prefix] : bucket name must be specified"
	exit 1
fi

# set the bucket nemae
bucket=$1

# set a prefix (optional, if not set, this will apply to the whole bucket)
defaultPrefix=""
PREFIX=${2:-$defaultPrefix}

#get the canonical user ID for the bucket owner
accountID="$(aws s3api list-buckets --output text --query 'Owner.ID')"

#find objects that are not owned by me

aws s3api list-objects --bucket $bucket --prefix "$PREFIX" --output text --query  'Contents[?Owner.ID!=`'$accountID'`].Key'
