#!/bin/bash

# restore Objects from Glacier, given a bucket name and a Prefix (optional) and number during which 
# the file needs to remain available

if [[ -z $1 ]]; then
	echo "Usage : $0 bucket_name [prefix] [restore_days]"
	echo ""
	echo -e "  \e[32mbucket_name \e[39m: Name of the bucket from which to restore files"
	echo -e "  \e[32mprefix \e[39m: prefix under which to look for files, defaults to \"\" which means whole bucket"
	echo -e "  \e[32mrestore_days \e[39m: Restore the files for restore_days days, default to 10"
	echo -e "  \e[32mType of restore \e[39m: Use Standard (default), Bulk or Expedited restore type"
	exit 1
fi

# set the bucket nemae
BUCKET=$1
echo "Chosen S3 bucket : $BUCKET"
# set a prefix (optional, if not set, this will apply to the whole bucket)
defaultPrefix=""
PREFIX=${2:-$defaultPrefix}
echo "Chosen Prefix : $PREFIX"
defaultDays=10
DAYS=${3:-$defaultDays}
echo "Number of restore days : $DAYS"
defaultTier="Standard"
TIER=${4:-$defaultTier}
echo "Type of Restore Job : $TIER"

set -e 
# get the list of the objects that are stored in Glacier
for a in  $(aws s3api list-objects --bucket "$BUCKET" --prefix "$PREFIX" --output text --query 'Contents[?StorageClass==`GLACIER`].Key');

        do
                echo "Restoring the following Object  -->  "   "$a"
		aws s3api restore-object --bucket "$BUCKET" --key "$a" --restore-request Days=$DAYS,GlacierJobParameters={Tier=$TIER} && echo "SUCCESS"
        done
